export const GET_SERVICES = "SERVICES/GET_SERVICES";
export const ADD_SERVICE = "SERVICES/ADD_SERVICE";
export const UPDATE_SERVICE = "SERVICES/UPDATE_SERVICE";
export const DELETE_SERVICE = "SERVICES/DELETE_SERVICE";
export const RESET_SERVICES = "SERVICES/RESET_SERVICES";

export const GET_COACHES = "COACHES/GET_COACHES";
export const ADD_COACH = "COACHES/ADD_COACH";
export const UPDATE_COACH = "COACHES/UPDATE_COACH";
export const DELETE_COACH = "COACHES/DELETE_COACH";
export const RESET_COACHES = "COACHES/RESET_COACHES";

export const GET_CLIENTS = "CLIENTS/GET_CLIENTS";
export const RESET_CLIENTS = "CLIENTS/RESET_CLIENTS";

export const GET_SLOTS = "SLOTS/GET_SLOTS";
export const ADD_SLOT = "SLOTS/ADD_SLOT";
export const UPDATE_SLOT = "SLOTS/UPDATE_SLOT";
export const DELETE_SLOT = "SLOTS/DELETE_SLOT";
export const RESET_SLOTS = "SLOTS/RESET_SLOTS";
