export const GET_SERVICES = "SERVICES/GET_SERVICES";
export const ADD_SERVICE = "SERVICES/ADD_SERVICE";
export const RESET_SERVICES = "SERVICES/RESET_SERVICES";

export const GET_COACHES = "COACHES/GET_COACHES";
export const ADD_COACH = "COACHES/ADD_COACH";
export const RESET_COACHES = "COACHES/RESET_COACHES";

export const GET_CLIENTS = "CLIENTS/GET_CLIENTS";
export const RESET_CLIENTS = "CLIENTS/RESET_CLIENTS";
